spring:
  application:
    name: item-service
  
  # 添加rabbitmq连接信息  
  rabbitmq:
    host: 192.168.75.133
    port: 5672
    username: admin
    password: admin
    
#server:
  #port: 8001
  
eureka:
  client:
    service-url:
      #defaultZone结合云服务器才能设置其它选项
           # 同时向eureka集群中的每台服务器都注册服务地址
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka

      
      
---
spring:
  profiles: item1
  
server:
  port: 8001
---
spring:
  profiles: item2

server:
  port: 8002